name: CI
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate composer.json and composer.lock
        run: composer validate
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
      - name: Run unit tests
        run: composer run test:unit
      - name: Report code coverage
        run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}

  release:
    needs: test
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_USER: shopware
          MYSQL_PASSWORD: shopware
        ports:
          - 3306
    steps:
      - uses: actions/checkout@v2
        if: startsWith(github.ref, 'refs/tags/')
      - name: Start MySQL
        if: startsWith(github.ref, 'refs/tags/')
        run: sudo /etc/init.d/mysql start
      - name: Build release zip
        if: startsWith(github.ref, 'refs/tags/')
        run: bin/build-release.sh
